spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online_shop
    username: user
    password: root
jwt:
  secret: YXNkZmYkIyNzZFNEU0RBQVNERksjQEBkc2ZqZGZrZHNqQEAjZHNmZ2ZnZmdeXiYmWipeJSQkI2RzZHMkIyVzZDQ1MDk5KUkjJCg5V0ZTSUo=
  expiration: 60000
server:
  port: 8083
